もっとシンプルにCargo buildする
GiganticMinecraft/seichi-portal-backend pull request #102
Opened 2023-03-18 05:40 UTC by inductor

2023-03-19 02:16 UTC, LoliGothick requested changes

2023-03-19 02:16 UTC, LoliGothick commented on Dockerfile
> +    cargo fetch --manifest-path server/Cargo.toml
```suggestion
    cargo fetch --manifest-path app/server/Cargo.toml
```

2023-03-19 08:45 UTC, LoliGothick requested changes

2023-03-19 08:45 UTC, LoliGothick commented on Dockerfile
> +    cargo fetch --manifest-path app/server/Cargo.toml
すいません、スラッシュ抜けてました・・・

```suggestion
    cargo fetch --manifest-path /app/server/Cargo.toml
```

2023-03-20 11:35 UTC, LoliGothick approved these changes

2023-03-20 12:46 UTC, rito528 approved these changes

2023-03-20 12:46 UTC, merged