フォーム情報を更新するためのエントリポイントを実装
GiganticMinecraft/seichi-portal-backend pull request #196
Opened 2023-06-25 07:59 UTC by rito528

2023-06-25 15:46 UTC, LoliGothick requested changes

2023-06-25 15:46 UTC, LoliGothick commented on server/presentation/src/form_handler.rs
> +        Ok(form) => (StatusCode::OK, Json(json!(form))).into_response(),
`json!` マクロ不要

2023-06-26 06:01 UTC, rito528 commented
@LoliGothick 
修正しました。
再レビューお願いします

2023-06-26 07:38 UTC, LoliGothick approved these changes

2023-06-27 04:44 UTC, merged