フォームの回答に対してコメントを付けるエンドポイントの実装
GiganticMinecraft/seichi-portal-backend pull request #356
Opened 2023-11-18 15:28 UTC by rito528

2023-11-29 10:18 UTC, LoliGothick requested changes

2023-11-29 10:18 UTC, LoliGothick commented on server/usecase/src/form.rs
> +                comment.to_owned().commented_by,
`to_owned()` をやめて参照にしてください、関連する関数のシグネチャにも `&` をつけて回って `derive(Clone)` を消してください。

2023-12-02 14:31 UTC, rito528 commented on server/usecase/src/form.rs
> +                comment.to_owned().commented_by,
`to_owned()`をやめて参照にすることはできたんですが、`derive(Clone)`を削除すると`into_inner()`が使えなくなり、`sea_orm::Value`に`into()`できなくなります。

2023-12-03 11:01 UTC, rito528 commented on server/usecase/src/form.rs
> +                comment.to_owned().commented_by,
なんでだろう....
もう少し試してみます

2023-12-03 11:42 UTC, LoliGothick commented on server/usecase/src/form.rs
> +                comment.to_owned().commented_by,
idまで参照で辿ってから `into_inner` してほしい

2023-12-09 10:13 UTC, LoliGothick approved these changes

2023-12-09 10:15 UTC, merged