Refactor docs
GiganticMinecraft/seichi-portal-backend pull request #52
Opened 2023-03-03 13:05 UTC by Lucky3028

2023-03-03 13:12 UTC, rito528 requested changes

2023-03-03 13:12 UTC, rito528 commented on README.md
> +フロントエンド実装については[こちらのリポジトリ](https://github.com/GiganticMinecraft/seichi-portal-frontend)を参照してください。
```suggestion
フロントエンド実装については[こちらのリポジトリ](https://github.com/GiganticMinecraft/seichi-portal-frontend)を参照してください。
```
関連リポジトリは5行目で別リポジトリを参照してくださいと言っているので、ここでフロントエンド実装について触れる必要はないと思います。

2023-03-03 13:12 UTC, rito528 commented on README.md
```suggestion
このリポジトリは Seichi Portal のバックエンド実装です。
```

2023-03-03 13:18 UTC, Lucky3028 commented
@rito528 API定義の項はどうしましょう？

2023-03-03 13:23 UTC, rito528 approved these changes

2023-03-03 13:23 UTC, merged

2023-03-03 13:25 UTC, Lucky3028 commented on README.md
> +このリポジトリは、Seichi Portalのバックエンド実装です。
日本語の文章なんですからスペースはおかしくないですか？

2023-03-03 13:25 UTC, Lucky3028 commented on README.md
> +このリポジトリは、Seichi Portalのバックエンド実装です。
@rito528

2023-03-04 02:05 UTC, rito528 commented on README.md
> +このリポジトリは、Seichi Portalのバックエンド実装です。
@Lucky3028 
読点が消えてるのは普通にミスで、その後にスペースを開けるという意図でした

2023-03-04 02:14 UTC, rito528 commented on README.md
> +このリポジトリは、Seichi Portalのバックエンド実装です。
@inductor さんや @kory33 さんよると、人によるけど開けたほうが好きとのことでした

2023-03-04 10:01 UTC, Lucky3028 commented on README.md
> +このリポジトリは、Seichi Portalのバックエンド実装です。
人による草
了解です