データベース構造の再設計
GiganticMinecraft/seichi-portal-backend pull request #91
Opened 2023-03-12 13:47 UTC by rito528

2023-03-12 16:02 UTC, LoliGothick reviewed
question type は ENUM型でいいのでは

2023-03-13 07:21 UTC, LoliGothick requested changes
question types 何かに使ってるのかな？
いらないのでは？

2023-03-13 09:00 UTC, rito528 commented
削除しました。

2023-03-13 10:19 UTC, LoliGothick approved these changes
よさそう

2023-03-13 10:19 UTC, merged

2023-03-13 11:23 UTC, rito528 commented
わ～い